-- Auto-generated by integration:apply for Snowflake

insert into public.companies (slug, name, website_url, careers_url, priority)
values
  (
    'snowflake',
    'Snowflake',
    'https://jobs.ashbyhq.com/snowflake',
    'https://jobs.ashbyhq.com/snowflake',
    41
  )
on conflict (slug) do update set
  name = excluded.name,
  website_url = excluded.website_url,
  careers_url = excluded.careers_url,
  priority = excluded.priority,
  is_active = true,
  updated_at = now();

insert into public.company_sources (
  company_id,
  source_type,
  adapter_key,
  source_url,
  board_token,
  enabled,
  scrape_interval_minutes
)
values
  (
    (select id from public.companies where slug = 'snowflake'),
    'ashby',
    'snowflake-ashby',
    'https://jobs.ashbyhq.com/snowflake',
    'snowflake',
    true,
    180
  );
