-- Expand Discover catalog (Greenhouse, Ashby, Lever). Board tokens probed via public APIs.
-- Skips Coinbase/Plaid 404 boards from migration 053; Shopify/Rippling remain disabled (084).

insert into public.companies (slug, name, website_url, careers_url, priority)
values
  ('twilio', 'Twilio', 'https://www.twilio.com', 'https://www.twilio.com/en-us/company/jobs', 43),
  ('okta', 'Okta', 'https://www.okta.com', 'https://www.okta.com/company/careers', 44),
  ('zscaler', 'Zscaler', 'https://www.zscaler.com', 'https://www.zscaler.com/careers', 45),
  ('lyft', 'Lyft', 'https://www.lyft.com', 'https://www.lyft.com/careers', 46),
  ('pinterest', 'Pinterest', 'https://www.pinterest.com', 'https://www.pinterestcareers.com', 47),
  ('affirm', 'Affirm', 'https://www.affirm.com', 'https://www.affirm.com/careers', 48),
  ('chime', 'Chime', 'https://www.chime.com', 'https://www.chime.com/careers', 49),
  ('mercury', 'Mercury', 'https://mercury.com', 'https://mercury.com/jobs', 50),
  ('flexport', 'Flexport', 'https://www.flexport.com', 'https://www.flexport.com/careers', 51),
  ('carta', 'Carta', 'https://carta.com', 'https://carta.com/careers', 52),
  ('duolingo', 'Duolingo', 'https://www.duolingo.com', 'https://careers.duolingo.com', 53),
  ('elastic', 'Elastic', 'https://www.elastic.co', 'https://www.elastic.co/careers', 54),
  ('cockroachlabs', 'Cockroach Labs', 'https://www.cockroachlabs.com', 'https://www.cockroachlabs.com/careers', 55),
  ('planetscale', 'PlanetScale', 'https://planetscale.com', 'https://planetscale.com/careers', 56),
  ('amplitude', 'Amplitude', 'https://amplitude.com', 'https://amplitude.com/careers', 57),
  ('launchdarkly', 'LaunchDarkly', 'https://launchdarkly.com', 'https://launchdarkly.com/careers', 58),
  ('waymo', 'Waymo', 'https://waymo.com', 'https://waymo.com/careers', 59),
  ('gitlab', 'GitLab', 'https://about.gitlab.com', 'https://about.gitlab.com/jobs', 60),
  ('mixpanel', 'Mixpanel', 'https://mixpanel.com', 'https://mixpanel.com/careers', 61),
  ('oscar', 'Oscar Health', 'https://www.hioscar.com', 'https://www.hioscar.com/careers', 62),
  ('toast', 'Toast', 'https://pos.toasttab.com', 'https://careers.toasttab.com', 63),
  ('uber-freight', 'Uber Freight', 'https://www.uberfreight.com', 'https://www.uberfreight.com/careers', 64),
  ('fastly', 'Fastly', 'https://www.fastly.com', 'https://www.fastly.com/about/careers', 65),
  ('lucid-motors', 'Lucid Motors', 'https://lucidmotors.com', 'https://lucidmotors.com/careers', 66),
  ('nuro', 'Nuro', 'https://www.nuro.ai', 'https://www.nuro.ai/careers', 67),
  ('applied-intuition', 'Applied Intuition', 'https://www.appliedintuition.com', 'https://www.appliedintuition.com/careers', 68),
  ('coinbase', 'Coinbase', 'https://www.coinbase.com', 'https://www.coinbase.com/careers', 69),
  ('supabase', 'Supabase', 'https://supabase.com', 'https://supabase.com/careers', 70),
  ('replit', 'Replit', 'https://replit.com', 'https://replit.com/careers', 71),
  ('posthog', 'PostHog', 'https://posthog.com', 'https://posthog.com/careers', 72),
  ('cohere', 'Cohere', 'https://cohere.com', 'https://cohere.com/careers', 73),
  ('anyscale', 'Anyscale', 'https://www.anyscale.com', 'https://www.anyscale.com/careers', 74),
  ('langchain', 'LangChain', 'https://www.langchain.com', 'https://www.langchain.com/careers', 75),
  ('harvey', 'Harvey', 'https://www.harvey.ai', 'https://www.harvey.ai/careers', 76),
  ('cursor', 'Cursor', 'https://cursor.com', 'https://cursor.com/careers', 77),
  ('modal', 'Modal', 'https://modal.com', 'https://modal.com/careers', 78),
  ('column', 'Column', 'https://column.com', 'https://column.com/careers', 79),
  ('render', 'Render', 'https://render.com', 'https://render.com/careers', 80),
  ('netflix', 'Netflix', 'https://www.netflix.com', 'https://jobs.netflix.com', 81),
  ('binance', 'Binance', 'https://www.binance.com', 'https://www.binance.com/en/careers', 82)
on conflict (slug) do update set
  name = excluded.name,
  website_url = excluded.website_url,
  careers_url = excluded.careers_url,
  priority = excluded.priority,
  is_active = true,
  updated_at = now();

insert into public.company_sources (
  company_id,
  source_type,
  adapter_key,
  source_url,
  board_token,
  enabled,
  scrape_interval_minutes
)
values
  ((select id from public.companies where slug = 'twilio'), 'greenhouse', 'twilio-greenhouse', 'https://boards.greenhouse.io/twilio', 'twilio', true, 240),
  ((select id from public.companies where slug = 'okta'), 'greenhouse', 'okta-greenhouse', 'https://boards.greenhouse.io/okta', 'okta', true, 240),
  ((select id from public.companies where slug = 'zscaler'), 'greenhouse', 'zscaler-greenhouse', 'https://boards.greenhouse.io/zscaler', 'zscaler', true, 240),
  ((select id from public.companies where slug = 'lyft'), 'greenhouse', 'lyft-greenhouse', 'https://boards.greenhouse.io/lyft', 'lyft', true, 240),
  ((select id from public.companies where slug = 'pinterest'), 'greenhouse', 'pinterest-greenhouse', 'https://boards.greenhouse.io/pinterest', 'pinterest', true, 240),
  ((select id from public.companies where slug = 'affirm'), 'greenhouse', 'affirm-greenhouse', 'https://boards.greenhouse.io/affirm', 'affirm', true, 240),
  ((select id from public.companies where slug = 'chime'), 'greenhouse', 'chime-greenhouse', 'https://boards.greenhouse.io/chime', 'chime', true, 240),
  ((select id from public.companies where slug = 'mercury'), 'greenhouse', 'mercury-greenhouse', 'https://boards.greenhouse.io/mercury', 'mercury', true, 240),
  ((select id from public.companies where slug = 'flexport'), 'greenhouse', 'flexport-greenhouse', 'https://boards.greenhouse.io/flexport', 'flexport', true, 240),
  ((select id from public.companies where slug = 'carta'), 'greenhouse', 'carta-greenhouse', 'https://boards.greenhouse.io/carta', 'carta', true, 240),
  ((select id from public.companies where slug = 'duolingo'), 'greenhouse', 'duolingo-greenhouse', 'https://boards.greenhouse.io/duolingo', 'duolingo', true, 240),
  ((select id from public.companies where slug = 'elastic'), 'greenhouse', 'elastic-greenhouse', 'https://boards.greenhouse.io/elastic', 'elastic', true, 240),
  ((select id from public.companies where slug = 'cockroachlabs'), 'greenhouse', 'cockroachlabs-greenhouse', 'https://boards.greenhouse.io/cockroachlabs', 'cockroachlabs', true, 240),
  ((select id from public.companies where slug = 'planetscale'), 'greenhouse', 'planetscale-greenhouse', 'https://boards.greenhouse.io/planetscale', 'planetscale', true, 240),
  ((select id from public.companies where slug = 'amplitude'), 'greenhouse', 'amplitude-greenhouse', 'https://boards.greenhouse.io/amplitude', 'amplitude', true, 240),
  ((select id from public.companies where slug = 'launchdarkly'), 'greenhouse', 'launchdarkly-greenhouse', 'https://boards.greenhouse.io/launchdarkly', 'launchdarkly', true, 240),
  ((select id from public.companies where slug = 'waymo'), 'greenhouse', 'waymo-greenhouse', 'https://boards.greenhouse.io/waymo', 'waymo', true, 240),
  ((select id from public.companies where slug = 'gitlab'), 'greenhouse', 'gitlab-greenhouse', 'https://boards.greenhouse.io/gitlab', 'gitlab', true, 240),
  ((select id from public.companies where slug = 'mixpanel'), 'greenhouse', 'mixpanel-greenhouse', 'https://boards.greenhouse.io/mixpanel', 'mixpanel', true, 240),
  ((select id from public.companies where slug = 'oscar'), 'greenhouse', 'oscar-greenhouse', 'https://boards.greenhouse.io/oscar', 'oscar', true, 240),
  ((select id from public.companies where slug = 'toast'), 'greenhouse', 'toast-greenhouse', 'https://boards.greenhouse.io/toast', 'toast', true, 240),
  ((select id from public.companies where slug = 'uber-freight'), 'greenhouse', 'uber-freight-greenhouse', 'https://boards.greenhouse.io/uberfreight', 'uberfreight', true, 240),
  ((select id from public.companies where slug = 'fastly'), 'greenhouse', 'fastly-greenhouse', 'https://boards.greenhouse.io/fastly', 'fastly', true, 240),
  ((select id from public.companies where slug = 'lucid-motors'), 'greenhouse', 'lucid-motors-greenhouse', 'https://boards.greenhouse.io/lucidmotors', 'lucidmotors', true, 240),
  ((select id from public.companies where slug = 'nuro'), 'greenhouse', 'nuro-greenhouse', 'https://boards.greenhouse.io/nuro', 'nuro', true, 240),
  ((select id from public.companies where slug = 'applied-intuition'), 'greenhouse', 'applied-intuition-greenhouse', 'https://boards.greenhouse.io/appliedintuition', 'appliedintuition', true, 240),
  ((select id from public.companies where slug = 'coinbase'), 'greenhouse', 'coinbase-greenhouse', 'https://boards.greenhouse.io/coinbase', 'coinbase', true, 240),
  ((select id from public.companies where slug = 'supabase'), 'ashby', 'supabase-ashby', 'https://jobs.ashbyhq.com/supabase', 'supabase', true, 240),
  ((select id from public.companies where slug = 'replit'), 'ashby', 'replit-ashby', 'https://jobs.ashbyhq.com/replit', 'replit', true, 240),
  ((select id from public.companies where slug = 'posthog'), 'ashby', 'posthog-ashby', 'https://jobs.ashbyhq.com/posthog', 'posthog', true, 240),
  ((select id from public.companies where slug = 'cohere'), 'ashby', 'cohere-ashby', 'https://jobs.ashbyhq.com/cohere', 'cohere', true, 240),
  ((select id from public.companies where slug = 'anyscale'), 'ashby', 'anyscale-ashby', 'https://jobs.ashbyhq.com/anyscale', 'anyscale', true, 240),
  ((select id from public.companies where slug = 'langchain'), 'ashby', 'langchain-ashby', 'https://jobs.ashbyhq.com/langchain', 'langchain', true, 240),
  ((select id from public.companies where slug = 'harvey'), 'ashby', 'harvey-ashby', 'https://jobs.ashbyhq.com/harvey', 'harvey', true, 240),
  ((select id from public.companies where slug = 'cursor'), 'ashby', 'cursor-ashby', 'https://jobs.ashbyhq.com/cursor', 'cursor', true, 240),
  ((select id from public.companies where slug = 'modal'), 'ashby', 'modal-ashby', 'https://jobs.ashbyhq.com/modal', 'modal', true, 240),
  ((select id from public.companies where slug = 'column'), 'ashby', 'column-ashby', 'https://jobs.ashbyhq.com/column', 'column', true, 240),
  ((select id from public.companies where slug = 'render'), 'ashby', 'render-ashby', 'https://jobs.ashbyhq.com/render', 'render', true, 240),
  ((select id from public.companies where slug = 'netflix'), 'lever', 'netflix-lever', 'https://jobs.lever.co/netflix', 'netflix', true, 240),
  ((select id from public.companies where slug = 'binance'), 'lever', 'binance-lever', 'https://jobs.lever.co/binance', 'binance', true, 240)
on conflict (
  company_id,
  source_type,
  adapter_key,
  coalesce(board_token, ''),
  coalesce(source_url, '')
) do update set
  source_url = excluded.source_url,
  board_token = excluded.board_token,
  enabled = true,
  last_error_code = null,
  scrape_interval_minutes = excluded.scrape_interval_minutes,
  updated_at = now();
