-- Company sources for 097 expansion (applied as 097b when 097 companies seed was split remotely).

insert into public.company_sources(
  company_id,
  source_type,
  adapter_key,
  source_url,
  board_token,
  enabled,
  scrape_interval_minutes
)
values
  ((select id from public.companies where slug = '10x-genomics'), 'greenhouse', '10x-genomics-greenhouse', 'https://job-boards.greenhouse.io/10xgenomics', '10xgenomics', true, 240),
  ((select id from public.companies where slug = 'adyen'), 'greenhouse', 'adyen-greenhouse', 'https://job-boards.greenhouse.io/adyen', 'adyen', true, 240),
  ((select id from public.companies where slug = 'airbyte'), 'ashby', 'airbyte-ashby', 'https://jobs.ashbyhq.com/airbyte', 'airbyte', true, 240),
  ((select id from public.companies where slug = 'anchorage'), 'lever', 'anchorage-lever', 'https://jobs.lever.co/anchorage', 'anchorage', true, 240),
  ((select id from public.companies where slug = 'astranis'), 'greenhouse', 'astranis-greenhouse', 'https://job-boards.greenhouse.io/astranis', 'astranis', true, 240),
  ((select id from public.companies where slug = 'baseten'), 'ashby', 'baseten-ashby', 'https://jobs.ashbyhq.com/baseten', 'baseten', true, 240),
  ((select id from public.companies where slug = 'bird'), 'greenhouse', 'bird-greenhouse', 'https://job-boards.greenhouse.io/bird', 'bird', true, 240),
  ((select id from public.companies where slug = 'blockchain'), 'greenhouse', 'blockchain-greenhouse', 'https://job-boards.greenhouse.io/blockchain', 'blockchain', true, 240),
  ((select id from public.companies where slug = 'buildkite'), 'greenhouse', 'buildkite-greenhouse', 'https://job-boards.greenhouse.io/buildkite', 'buildkite', true, 240),
  ((select id from public.companies where slug = 'canonical'), 'greenhouse', 'canonical-greenhouse', 'https://job-boards.greenhouse.io/canonical', 'canonical', true, 240),
  ((select id from public.companies where slug = 'chargepoint'), 'greenhouse', 'chargepoint-greenhouse', 'https://job-boards.greenhouse.io/chargepoint', 'chargepoint', true, 240),
  ((select id from public.companies where slug = 'circleci'), 'greenhouse', 'circleci-greenhouse', 'https://job-boards.greenhouse.io/circleci', 'circleci', true, 240),
  ((select id from public.companies where slug = 'clover-health'), 'greenhouse', 'clover-health-greenhouse', 'https://job-boards.greenhouse.io/cloverhealth', 'cloverhealth', true, 240),
  ((select id from public.companies where slug = 'coder'), 'ashby', 'coder-ashby', 'https://jobs.ashbyhq.com/coder', 'coder', true, 240),
  ((select id from public.companies where slug = 'coreweave'), 'greenhouse', 'coreweave-greenhouse', 'https://job-boards.greenhouse.io/coreweave', 'coreweave', true, 240),
  ((select id from public.companies where slug = 'drata'), 'ashby', 'drata-ashby', 'https://jobs.ashbyhq.com/drata', 'drata', true, 240),
  ((select id from public.companies where slug = 'dust'), 'ashby', 'dust-ashby', 'https://jobs.ashbyhq.com/dust', 'dust', true, 240),
  ((select id from public.companies where slug = 'faire'), 'greenhouse', 'faire-greenhouse', 'https://job-boards.greenhouse.io/faire', 'faire', true, 240),
  ((select id from public.companies where slug = 'figure'), 'greenhouse', 'figure-greenhouse', 'https://job-boards.greenhouse.io/figure', 'figure', true, 240),
  ((select id from public.companies where slug = 'fireblocks'), 'greenhouse', 'fireblocks-greenhouse', 'https://job-boards.greenhouse.io/fireblocks', 'fireblocks', true, 240),
  ((select id from public.companies where slug = 'fullstory'), 'ashby', 'fullstory-ashby', 'https://jobs.ashbyhq.com/fullstory', 'fullstory', true, 240),
  ((select id from public.companies where slug = 'glossier'), 'greenhouse', 'glossier-greenhouse', 'https://job-boards.greenhouse.io/glossier', 'glossier', true, 240),
  ((select id from public.companies where slug = 'gopuff'), 'lever', 'gopuff-lever', 'https://jobs.lever.co/gopuff', 'gopuff', true, 240),
  ((select id from public.companies where slug = 'highnote'), 'greenhouse', 'highnote-greenhouse', 'https://job-boards.greenhouse.io/highnote', 'highnote', true, 240),
  ((select id from public.companies where slug = 'lambda'), 'ashby', 'lambda-ashby', 'https://jobs.ashbyhq.com/lambda', 'lambda', true, 240),
  ((select id from public.companies where slug = 'lightdash'), 'ashby', 'lightdash-ashby', 'https://jobs.ashbyhq.com/lightdash', 'lightdash', true, 240),
  ((select id from public.companies where slug = 'lithic'), 'greenhouse', 'lithic-greenhouse', 'https://job-boards.greenhouse.io/lithic', 'lithic', true, 240),
  ((select id from public.companies where slug = 'lovable'), 'ashby', 'lovable-ashby', 'https://jobs.ashbyhq.com/lovable', 'lovable', true, 240),
  ((select id from public.companies where slug = 'materialize'), 'ashby', 'materialize-ashby', 'https://jobs.ashbyhq.com/materialize', 'materialize', true, 240),
  ((select id from public.companies where slug = 'middesk'), 'ashby', 'middesk-ashby', 'https://jobs.ashbyhq.com/middesk', 'middesk', true, 240),
  ((select id from public.companies where slug = 'mistral'), 'lever', 'mistral-lever', 'https://jobs.lever.co/mistral', 'mistral', true, 240),
  ((select id from public.companies where slug = 'motherduck'), 'ashby', 'motherduck-ashby', 'https://jobs.ashbyhq.com/motherduck', 'motherduck', true, 240),
  ((select id from public.companies where slug = 'omni'), 'ashby', 'omni-ashby', 'https://jobs.ashbyhq.com/omni', 'omni', true, 240),
  ((select id from public.companies where slug = 'oscilar'), 'ashby', 'oscilar-ashby', 'https://jobs.ashbyhq.com/oscilar', 'oscilar', true, 240),
  ((select id from public.companies where slug = 'oura'), 'greenhouse', 'oura-greenhouse', 'https://job-boards.greenhouse.io/oura', 'oura', true, 240),
  ((select id from public.companies where slug = 'payoneer'), 'greenhouse', 'payoneer-greenhouse', 'https://job-boards.greenhouse.io/payoneer', 'payoneer', true, 240),
  ((select id from public.companies where slug = 'peloton'), 'greenhouse', 'peloton-greenhouse', 'https://job-boards.greenhouse.io/peloton', 'peloton', true, 240),
  ((select id from public.companies where slug = 'persona'), 'ashby', 'persona-ashby', 'https://jobs.ashbyhq.com/persona', 'persona', true, 240),
  ((select id from public.companies where slug = 'prefect'), 'ashby', 'prefect-ashby', 'https://jobs.ashbyhq.com/prefect', 'prefect', true, 240),
  ((select id from public.companies where slug = 'railway'), 'ashby', 'railway-ashby', 'https://jobs.ashbyhq.com/railway', 'railway', true, 240),
  ((select id from public.companies where slug = 'redis'), 'ashby', 'redis-ashby', 'https://jobs.ashbyhq.com/redis', 'redis', true, 240),
  ((select id from public.companies where slug = 'relativity'), 'greenhouse', 'relativity-greenhouse', 'https://job-boards.greenhouse.io/relativity', 'relativity', true, 240),
  ((select id from public.companies where slug = 'rent-the-runway'), 'greenhouse', 'rent-the-runway-greenhouse', 'https://job-boards.greenhouse.io/renttherunway', 'renttherunway', true, 240),
  ((select id from public.companies where slug = 'ripple'), 'greenhouse', 'ripple-greenhouse', 'https://job-boards.greenhouse.io/ripple', 'ripple', true, 240),
  ((select id from public.companies where slug = 'rocket-lab'), 'greenhouse', 'rocket-lab-greenhouse', 'https://job-boards.greenhouse.io/rocketlab', 'rocketlab', true, 240),
  ((select id from public.companies where slug = 'rubrik'), 'greenhouse', 'rubrik-greenhouse', 'https://job-boards.greenhouse.io/rubrik', 'rubrik', true, 240),
  ((select id from public.companies where slug = 'sanity'), 'ashby', 'sanity-ashby', 'https://jobs.ashbyhq.com/sanity', 'sanity', true, 240),
  ((select id from public.companies where slug = 'scopely'), 'greenhouse', 'scopely-greenhouse', 'https://job-boards.greenhouse.io/scopely', 'scopely', true, 240),
  ((select id from public.companies where slug = 'sentilink'), 'ashby', 'sentilink-ashby', 'https://jobs.ashbyhq.com/sentilink', 'sentilink', true, 240),
  ((select id from public.companies where slug = 'sezzle'), 'greenhouse', 'sezzle-greenhouse', 'https://job-boards.greenhouse.io/sezzle', 'sezzle', true, 240),
  ((select id from public.companies where slug = 'sift'), 'ashby', 'sift-ashby', 'https://jobs.ashbyhq.com/sift', 'sift', true, 240),
  ((select id from public.companies where slug = 'skydio'), 'ashby', 'skydio-ashby', 'https://jobs.ashbyhq.com/skydio', 'skydio', true, 240),
  ((select id from public.companies where slug = 'socure'), 'ashby', 'socure-ashby', 'https://jobs.ashbyhq.com/socure', 'socure', true, 240),
  ((select id from public.companies where slug = 'statsig'), 'ashby', 'statsig-ashby', 'https://jobs.ashbyhq.com/statsig', 'statsig', true, 240),
  ((select id from public.companies where slug = 'stitch-fix'), 'greenhouse', 'stitch-fix-greenhouse', 'https://job-boards.greenhouse.io/stitchfix', 'stitchfix', true, 240),
  ((select id from public.companies where slug = 'take-two'), 'greenhouse', 'take-two-greenhouse', 'https://job-boards.greenhouse.io/taketwo', 'taketwo', true, 240),
  ((select id from public.companies where slug = 'thumbtack'), 'ashby', 'thumbtack-ashby', 'https://jobs.ashbyhq.com/thumbtack', 'thumbtack', true, 240),
  ((select id from public.companies where slug = 'together-ai'), 'greenhouse', 'together-ai-greenhouse', 'https://job-boards.greenhouse.io/togetherai', 'togetherai', true, 240),
  ((select id from public.companies where slug = 'twitch'), 'greenhouse', 'twitch-greenhouse', 'https://job-boards.greenhouse.io/twitch', 'twitch', true, 240),
  ((select id from public.companies where slug = 'vanta'), 'ashby', 'vanta-ashby', 'https://jobs.ashbyhq.com/vanta', 'vanta', true, 240),
  ((select id from public.companies where slug = 'writer'), 'ashby', 'writer-ashby', 'https://jobs.ashbyhq.com/writer', 'writer', true, 240),
  ((select id from public.companies where slug = 'zoox'), 'lever', 'zoox-lever', 'https://jobs.lever.co/zoox', 'zoox', true, 240)
on conflict (
  company_id,
  source_type,
  adapter_key,
  coalesce(board_token, ''),
  coalesce(source_url, '')
) do update set
  source_url = excluded.source_url,
  board_token = excluded.board_token,
  enabled = true,
  last_error_code = null,
  scrape_interval_minutes = excluded.scrape_interval_minutes,
  updated_at = now();