import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Banknote,
  Bitcoin,
  Bot,
  Brain,
  Building2,
  Car,
  Cloud,
  Cpu,
  Database,
  Gamepad2,
  Globe,
  HeartPulse,
  Landmark,
  Layers,
  LineChart,
  Monitor,
  Plane,
  Radio,
  Rocket,
  Shield,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Truck,
  Users,
  Wrench,
  Zap,
} from "lucide-react";

const INDUSTRY_ICONS: Record<string, LucideIcon> = {
  platform: Monitor,
  semiconductor: Cpu,
  networking: Radio,
  "ai-research": Brain,
  "ai-products": Sparkles,
  "ai-infrastructure": Layers,
  "life-sciences": Activity,
  payments: Banknote,
  fintech: LineChart,
  banking: Landmark,
  crypto: Bitcoin,
  cloud: Cloud,
  data: Database,
  devtools: Wrench,
  cybersecurity: Shield,
  defense: Shield,
  space: Rocket,
  aviation: Plane,
  automotive: Car,
  "autonomous-vehicles": Bot,
  robotics: Bot,
  drones: Zap,
  quant: LineChart,
  gaming: Gamepad2,
  streaming: Monitor,
  social: Users,
  marketplaces: Store,
  "on-demand": Truck,
  ecommerce: ShoppingCart,
  "enterprise-software": Building2,
  productivity: Layers,
  "hr-tech": Users,
  healthtech: HeartPulse,
  "consumer-tech": Smartphone,
};

export function getDiscoverIndustryIcon(slug: string): LucideIcon {
  return INDUSTRY_ICONS[slug] ?? Globe;
}
