import type { QueueCompany } from "./integration-queue.ts";

/** Initial backlog toward ~500 FAANG+ targets. Curate `autoApprove` / tokens as you learn ATS patterns. */
export const PENDING_INTEGRATION_SEEDS: Omit<
  QueueCompany,
  "status" | "claimedAt" | "claimedBy" | "completedAt" | "lastVerifiedAt" | "postingsFound"
>[] = [
  // Tier C — custom careers (human-primed; autoApprove false)
  { slug: "apple", name: "Apple", careersUrl: "https://jobs.apple.com", tier: "custom", priority: 1, autoApprove: false },
  { slug: "google", name: "Google", careersUrl: "https://www.google.com/about/careers/applications", tier: "custom", priority: 2, autoApprove: false },
  { slug: "meta", name: "Meta", careersUrl: "https://www.metacareers.com/jobs", tier: "custom", priority: 3, autoApprove: false },
  { slug: "microsoft", name: "Microsoft", careersUrl: "https://jobs.careers.microsoft.com", tier: "custom", priority: 4, autoApprove: false },
  { slug: "tesla", name: "Tesla", careersUrl: "https://www.tesla.com/careers/search", tier: "custom", priority: 5, autoApprove: false },
  { slug: "citadel", name: "Citadel", careersUrl: "https://www.citadel.com/careers", tier: "custom", priority: 6, autoApprove: false },
  { slug: "netflix", name: "Netflix", careersUrl: "https://jobs.netflix.com", tier: "custom", priority: 7, autoApprove: false },
  { slug: "uber", name: "Uber", careersUrl: "https://www.uber.com/us/en/careers", tier: "custom", priority: 8, autoApprove: false },
  { slug: "lyft", name: "Lyft", careersUrl: "https://www.lyft.com/careers", tier: "custom", priority: 9, autoApprove: false },
  { slug: "doordash", name: "DoorDash", careersUrl: "https://careers.doordash.com", tier: "custom", priority: 10, autoApprove: false },
  { slug: "salesforce", name: "Salesforce", careersUrl: "https://careers.salesforce.com", tier: "custom", priority: 11, autoApprove: false },
  { slug: "adobe", name: "Adobe", careersUrl: "https://careers.adobe.com", tier: "custom", priority: 12, autoApprove: false },
  { slug: "oracle", name: "Oracle", careersUrl: "https://careers.oracle.com", tier: "custom", priority: 13, autoApprove: false },
  { slug: "ibm", name: "IBM", careersUrl: "https://www.ibm.com/careers", tier: "custom", priority: 14, autoApprove: false },
  { slug: "intel", name: "Intel", careersUrl: "https://jobs.intel.com", tier: "custom", priority: 15, autoApprove: false },
  { slug: "amd", name: "AMD", careersUrl: "https://careers.amd.com", tier: "custom", priority: 16, autoApprove: false },
  { slug: "qualcomm", name: "Qualcomm", careersUrl: "https://careers.qualcomm.com", tier: "custom", priority: 17, autoApprove: false },
  { slug: "jane-street", name: "Jane Street", careersUrl: "https://www.janestreet.com/join-jane-street/open-roles", tier: "custom", priority: 18, autoApprove: false, notes: "Adapter exists; queue entry for verify/sync only" },

  // Quant / trading — often custom
  { slug: "two-sigma", name: "Two Sigma", careersUrl: "https://careers.twosigma.com", tier: "discover", priority: 20, autoApprove: false },
  { slug: "hudson-river-trading", name: "Hudson River Trading", careersUrl: "https://www.hudsonrivertrading.com/careers", tier: "discover", priority: 21, autoApprove: false },
  { slug: "de-shaw", name: "DE Shaw", careersUrl: "https://www.deshaw.com/careers", tier: "discover", priority: 22, autoApprove: false },
  { slug: "jump-trading", name: "Jump Trading", careersUrl: "https://www.jumptrading.com/careers", tier: "discover", priority: 23, autoApprove: false },
  { slug: "virtu", name: "Virtu Financial", careersUrl: "https://www.virtu.com/careers", tier: "discover", priority: 24, autoApprove: false },
  { slug: "imc", name: "IMC", careersUrl: "https://www.imc.com/careers", tier: "discover", priority: 25, autoApprove: false },
  { slug: "akuna", name: "Akuna Capital", careersUrl: "https://www.akunacapital.com/careers", tier: "discover", priority: 26, autoApprove: false },
  { slug: "citadel-securities", name: "Citadel Securities", careersUrl: "https://www.citadelsecurities.com/careers", tier: "discover", priority: 27, autoApprove: false },
  { slug: "millennium", name: "Millennium", careersUrl: "https://www.mlp.com/careers", tier: "discover", priority: 28, autoApprove: false },
  { slug: "point72", name: "Point72", careersUrl: "https://careers.point72.com", tier: "discover", priority: 29, autoApprove: false },

  // Tier A — Greenhouse (autoApprove; confirm tokens in PR if verify fails)
  { slug: "databricks", name: "Databricks", careersUrl: "https://www.databricks.com/company/careers", tier: "greenhouse", priority: 40, autoApprove: true, boardToken: "databricks" },
  { slug: "snowflake", name: "Snowflake", careersUrl: "https://careers.snowflake.com", tier: "greenhouse", priority: 41, autoApprove: true, boardToken: "snowflake" },
  { slug: "mongodb", name: "MongoDB", careersUrl: "https://www.mongodb.com/careers", tier: "greenhouse", priority: 42, autoApprove: true, boardToken: "mongodb" },
  { slug: "cloudflare", name: "Cloudflare", careersUrl: "https://www.cloudflare.com/careers", tier: "greenhouse", priority: 43, autoApprove: true, boardToken: "cloudflare" },
  { slug: "pinterest", name: "Pinterest", careersUrl: "https://www.pinterestcareers.com", tier: "greenhouse", priority: 44, autoApprove: true, boardToken: "pinterest" },
  { slug: "snap", name: "Snap", careersUrl: "https://careers.snap.com", tier: "greenhouse", priority: 45, autoApprove: true, boardToken: "snap" },
  { slug: "block", name: "Block", careersUrl: "https://block.xyz/careers", tier: "greenhouse", priority: 46, autoApprove: true, boardToken: "block" },
  { slug: "instacart", name: "Instacart", careersUrl: "https://instacart.careers", tier: "greenhouse", priority: 47, autoApprove: true, boardToken: "instacart" },
  { slug: "hubspot", name: "HubSpot", careersUrl: "https://www.hubspot.com/careers", tier: "greenhouse", priority: 48, autoApprove: true, boardToken: "hubspot" },
  { slug: "twilio", name: "Twilio", careersUrl: "https://www.twilio.com/company/jobs", tier: "greenhouse", priority: 49, autoApprove: true, boardToken: "twilio" },
  { slug: "okta", name: "Okta", careersUrl: "https://www.okta.com/company/careers", tier: "greenhouse", priority: 50, autoApprove: true, boardToken: "okta" },
  { slug: "elastic", name: "Elastic", careersUrl: "https://www.elastic.co/careers", tier: "greenhouse", priority: 51, autoApprove: true, boardToken: "elastic" },
  { slug: "gitlab", name: "GitLab", careersUrl: "https://about.gitlab.com/jobs", tier: "greenhouse", priority: 52, autoApprove: true, boardToken: "gitlab" },
  { slug: "hashicorp", name: "HashiCorp", careersUrl: "https://www.hashicorp.com/careers", tier: "greenhouse", priority: 53, autoApprove: true, boardToken: "hashicorp" },
  { slug: "confluent", name: "Confluent", careersUrl: "https://careers.confluent.io", tier: "greenhouse", priority: 54, autoApprove: true, boardToken: "confluent" },
  { slug: "cockroach-labs", name: "Cockroach Labs", careersUrl: "https://www.cockroachlabs.com/careers", tier: "greenhouse", priority: 55, autoApprove: true, boardToken: "cockroachlabs" },
  { slug: "scale-ai", name: "Scale AI", careersUrl: "https://scale.com/careers", tier: "greenhouse", priority: 56, autoApprove: true, boardToken: "scaleai" },
  { slug: "anduril", name: "Anduril", careersUrl: "https://www.anduril.com/careers", tier: "greenhouse", priority: 57, autoApprove: true, boardToken: "anduril" },
  { slug: "palantir", name: "Palantir", careersUrl: "https://www.palantir.com/careers", tier: "lever", priority: 58, autoApprove: true, boardToken: "palantir", notes: "May already exist in DB from 050" },
  { slug: "spotify", name: "Spotify", careersUrl: "https://www.lifeatspotify.com/jobs", tier: "lever", priority: 59, autoApprove: true, boardToken: "spotify" },
  { slug: "cruise", name: "Cruise", careersUrl: "https://www.getcruise.com/careers", tier: "greenhouse", priority: 60, autoApprove: true, boardToken: "getcruise" },
  { slug: "waymo", name: "Waymo", careersUrl: "https://waymo.com/careers", tier: "greenhouse", priority: 61, autoApprove: true, boardToken: "waymo" },
  { slug: "rivian", name: "Rivian", careersUrl: "https://careers.rivian.com", tier: "greenhouse", priority: 62, autoApprove: true, boardToken: "rivian" },
  { slug: "figma", name: "Figma", careersUrl: "https://www.figma.com/careers", tier: "greenhouse", priority: 63, autoApprove: true, boardToken: "figma", notes: "May already exist in DB" },

  // Tier B — discover ATS first
  { slug: "spacex", name: "SpaceX", careersUrl: "https://www.spacex.com/careers", tier: "discover", priority: 70, autoApprove: false },
  { slug: "tiktok", name: "TikTok", careersUrl: "https://careers.tiktok.com", tier: "discover", priority: 71, autoApprove: false },
  { slug: "bytedance", name: "ByteDance", careersUrl: "https://jobs.bytedance.com", tier: "discover", priority: 72, autoApprove: false },
  { slug: "shopify", name: "Shopify", careersUrl: "https://www.shopify.com/careers", tier: "discover", priority: 73, autoApprove: false },
  { slug: "squarespace", name: "Squarespace", careersUrl: "https://www.squarespace.com/careers", tier: "discover", priority: 74, autoApprove: false },
  { slug: "toast", name: "Toast", careersUrl: "https://careers.toasttab.com", tier: "discover", priority: 75, autoApprove: false },
  { slug: "sofi", name: "SoFi", careersUrl: "https://www.sofi.com/careers", tier: "discover", priority: 76, autoApprove: false },
  { slug: "chime", name: "Chime", careersUrl: "https://www.chime.com/careers", tier: "discover", priority: 77, autoApprove: false },
  { slug: "affirm", name: "Affirm", careersUrl: "https://www.affirm.com/careers", tier: "discover", priority: 78, autoApprove: false },
  { slug: "marqeta", name: "Marqeta", careersUrl: "https://www.marqeta.com/careers", tier: "discover", priority: 79, autoApprove: false },
  { slug: "carta", name: "Carta", careersUrl: "https://cart.com/careers", tier: "discover", priority: 80, autoApprove: false },
  { slug: "rippling", name: "Rippling", careersUrl: "https://www.rippling.com/careers", tier: "discover", priority: 81, autoApprove: false },
  { slug: "glean", name: "Glean", careersUrl: "https://www.glean.com/careers", tier: "discover", priority: 82, autoApprove: false },
  { slug: "cohere", name: "Cohere", careersUrl: "https://cohere.com/careers", tier: "discover", priority: 83, autoApprove: false },
  { slug: "mistral", name: "Mistral", careersUrl: "https://mistral.ai/careers", tier: "discover", priority: 84, autoApprove: false },
  { slug: "xai", name: "xAI", careersUrl: "https://x.ai/careers", tier: "discover", priority: 85, autoApprove: false },
  { slug: "character-ai", name: "Character.AI", careersUrl: "https://character.ai/careers", tier: "discover", priority: 86, autoApprove: false },
];
